services:
  - type: web
    name: cloud-access-shield-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USERNAME
        sync: false
      - key: COGNODB_PASSWORD
        sync: false
